# -*- coding: utf-8 -*-
"""NGC2_Annisa Triana Talmera

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nJoPYFmgx-G_k171VG_upWnMlOHMKfHX
"""

# Python program to print Even Numbers in a List

print("NCG 2")
print("by Annisa Triana Talmera")
print("_________________________")
 
# list of numbers
numbers = [951, 402, 984, 651, 360, 69, 408, 319, 601, 485, 980, 507, 725, 547, 544, 615, 83, 165, 141, 501, 263, 617, 865, 575, 219, 390, 984, 592, 236, 105, 942, 941, 386, 462, 47, 418, 907, 344, 236, 375, 823, 566, 597, 978, 328, 615, 953, 345, 399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949]

print("\nEven List Numbers : ")
#print("____________________")

# iterating each number in list
for num in numbers:

    # checking condition
   if num % 2 == 0:
      #if num <= 918:
        #continue
        print(num, end=" ")     #end= " " itu buat ganti urutan angka jadi ke samping, kalau gaada ini, urutannya ke bawah
        if num == 918:          #Proses dihentikan saat terdapat angka 918 pada proses looping
          break

print("\n\nDONE")

# Python program to print even Numbers in a List
 
print("NCG 2")
print("by Annisa Triana Talmera")
print("\n_________________________")

# list of numbers
n = [951, 402, 984, 651, 360, 69, 408, 319, 601, 485, 980, 507, 725, 547, 544, 615, 83, 165, 141, 501, 263, 617, 865, 575, 219, 390, 984, 592, 236, 105, 942, 941, 386, 462, 47, 418, 907, 344, 236, 375, 823, 566, 597, 978, 328, 615, 953, 345, 399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949]

print("\nList number", i)
print("\n_________________________")


# using list comprehension
evens = [num for num in n if num % 2 == 0]
 
print("\nEven numbers in the list: ", evens)


# stop looping while number = 918

new_list = [num for num in evens if num <= 918]
new_list.sort()

print("\nNew list number :", new_list)

print("\n__________________________")
print("\nDone")